### ISSUE TITLE
Can't locate utils.pm in @INC 

### ISSUE THREAD

**Issue by uncelvel** [RULCSoft/check_kannel#3]
Hi guys. 
When i check kannel with this plugin it have some problem
Can't locate utils.pm in @INC (@INC contains: /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /root/check_kannel line 30.
BEGIN failed--compilation aborted at /root/check_kannel line 30.
What can i do fix thix??

**Comment by uncelvel** [comment]
Oh i found this use lib "usr/lib/nagios/plugins/"; change to the usr/local/nagios/libexec problem is resolve

**Comment by loharp** [comment]
Hi Guys,
I am trying to run a parallel fragment extraction tool, provided by the work of "Accurate Parallel Fragment Extraction from Quasi–Comparable Corpora using Alignment Model
and Translation Lexicon, Chu+, IJCNLP2013". There are many perl scripts many of which are running without any issues. I am running from the beginning and now stuck in "combLex.pl". I ran this script with the following parameters,

perl script/combLex.pl -in_path data/dict/sampLex/iters/ -out_path data/dict/sampLex/ -iters 10

but it displays the following error:

Can't locate Util.pm in @INC (you may need to install the Util module) (@INC contains: /usr/share/doc/perl-modules-5.22 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at script/combLex.pl line 14.
BEGIN failed--compilation aborted at script/combLex.pl line 14.

I installed perl util and it looked like successful installation. Initially, in this script there was a line "use lib '/home/chu/tools/perl-module';" which I replaced by "use lib '/usr/share/doc/perl-modules-5.22';" but it still shows error.

I am a perl beginner, probably I am missing something, please help.

Thanks in advance,
Pintu
